### ISSUE TITLE
It seems that window_stack can be empty sometimes

### ISSUE THREAD

**Issue by fabio-blanco** [olivierlemoal/i3-swap-focus#2]
Wile executing this code, sometimes I got this error:

```
Task exception was never retrieved
future: <Task finished coro=<on_signal() done, defined at /home/my-user/bin/i3-swap-focus:15> exception=AttributeError("'NoneType' object has no attribute 'workspace'",)>
Traceback (most recent call last):
  File "/home/my-user/bin/i3-swap-focus", line 20, in on_signal
    window_workspace = (await i3.get_tree()).find_by_id(window_id).workspace().id
AttributeError: 'NoneType' object has no attribute 'workspace'
```

My i3wm version is 4.19 running on an Ubuntu 18.04 with three monitors with this configuration:

Monitor 1: workspaces 1, 4 and 6
Monitor 2: workspaces 2 and 5
Monitor 3: workspace 3

On the workspace 5 I have 12 Intellij windows and I was using i3-swap-focus to change mainly between those windows while sometimes interacting with workspace 1 where I have two terminal windows. I'm using the --stay-in-workspace parameter.
Sometimes when I came back from workspace 1 to workspace 2 and try the key combination to call i3-swap-focus the error happens.

Because I am on Ubuntu 18.04, I'm still using it's default Python 3.6.9 so I had to make some adaptations on your original code due to incompatibility with `asyncio.create_task`, `argparse.BooleanOptionalAction`, `asyncio.run` (added just on python 3.7 or 3.8):

```python
#loop.add_signal_handler(signal.SIGUSR1, lambda: asyncio.create_task(on_signal(i3)))
loop.add_signal_handler(signal.SIGUSR1, lambda: loop.create_task(on_signal(i3)))
```
```python
#parser.add_argument('--stay-in-workspace', action=argparse.BooleanOptionalAction, default=False, help="Do not switch focus if window is on a different workspace")
parser.add_argument('--stay-in-workspace', default=False, help="Do not switch focus if window is on a different workspace")
stay_in_workspace = parser.parse_args().stay_in_workspace
#asyncio.run(main())
main_loop = asyncio.get_event_loop()
main_loop.run_until_complete(main())
```

**Comment by olivierlemoal** [comment]
Hello fabio,
I just merged the PR, thanks a lot !

**Comment by fabio-blanco** [comment]
I don't know if you're interested in maintain a branch for older python versions too. I've made a pyhton < 3.7 version of your script for my personal use but I can share it with you if you think it may be useful.

Also as a suggestion I think you could put an open source license on this repository and make your code open source for real since it is already a public repository.

**Comment by olivierlemoal** [comment]
Hello Fabio !
Sure, feel free to fork the repo, I can merge your Python < 3.7 code into a separate branch.
Code is under MIT License as specified in `setup.py`: https://github.com/olivierlemoal/i3-swap-focus/blob/master/setup.py#L12
I will explicitly add the license in Github.

**Comment by fabio-blanco** [comment]
MIT is a good open source license and I think It will be great to explicitly add a LICENCE file on github too! [Here is one of mine](https://github.com/fabio-blanco/spring-boot-angular-security/blob/master/LICENSE) if you want some sample. Feel free to use it and just change the copyright for yours. It would be nice to place a reference to the license in the bottom of your readme too if you think it can be a good thing.

Do you want to create the separate branch in advance so I make the PR already directed to it or can I direct it to your master and you change it latter?

**Comment by olivierlemoal** [comment]
You can use this branch for the PR : https://github.com/olivierlemoal/i3-swap-focus/tree/python-3.6-support

**Comment by fabio-blanco** [comment]
Unfortunately today I was working and using the i3-swap-focus script and I've found one more situation where the error still persists. I have already made the correction (a protection on the code) but I will keep using my setup a little more to make sure the bug was really fixed before submitting another PR. :disappointed:

**Comment by fabio-blanco** [comment]
I think now I've covered the corners that still was uncovered. :+1: (see PR #5 )
Please test it before merge to assure I didn't break anything (remember... my python is still 3.6.9 so I've tested the old python version only)

**Comment by olivierlemoal** [comment]
Thanks for the PR Fabio :+1:
